name = "cmpt362-rooms-backend"
main = "src/index.ts"
compatibility_date = "2025-11-04"

[vars]
ROOM_CODE_LEN = "6"
ROOM_TTL_SEC = "300"

[[durable_objects.bindings]]
name = "ROOMS_DO"
class_name = "RoomsDOv2"

[[migrations]]
tag = "v1-initial"
new_sqlite_classes = ["RoomsDO"]

[[migrations]]
tag = "v2-reset"
new_sqlite_classes = ["RoomsDOv2"]
